# Generated by Django 3.2.24 on 2024-10-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_booking',
            name='name',
        ),
    ]
