# Generated by Django 3.2.24 on 2024-10-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_hotel_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_booking',
            name='name',
        ),
    ]
