# Generated by Django 3.2.24 on 2024-10-21 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20241021_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('GUIDE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guide')),
                ('PACKAGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
