# Generated by Django 3.2.24 on 2024-10-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_package_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('PACKAGE_BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package_booking')),
            ],
        ),
    ]
