# Generated by Django 3.2.24 on 2024-10-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_packagepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
